baseURL = "https://massadas.com/"
languageCode = "en-us"
title = "Gabriel Portfolio"
theme = "hyde"
canonifyURLs = true

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/g4brym/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabriel-massadas/"},
      {Name = "Medium", URL = "https://medium.com/@g4brym"}
  ]

[params]
  description = "Python developer mainly in Serverless and Django, based in Lisbon"
